//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpandables.Net.Api.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataAnnotations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataAnnotations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xpandables.Net.Api.I18n.DataAnnotations", typeof(DataAnnotations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les informations suivantes sont obligatoires : {0}.
        /// </summary>
        public static string AddressFormatAttribute {
            get {
                return ResourceManager.GetString("AddressFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&quot;âge doit être compris entre {1} et {2} ans..
        /// </summary>
        public static string AgeFormatAttribute {
            get {
                return ResourceManager.GetString("AgeFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la valeur &apos;{0}&apos; n&apos;est pas valide pour {1}..
        /// </summary>
        public static string BindingAttemptedvalueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("BindingAttemptedvalueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une valeur pour la propriété &apos;{0}&apos; est attendue..
        /// </summary>
        public static string BindingMissingBindRequiredValueAccessor {
            get {
                return ResourceManager.GetString("BindingMissingBindRequiredValueAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une valeur est attendue..
        /// </summary>
        public static string BindingMissingKeyOrValueAccessor {
            get {
                return ResourceManager.GetString("BindingMissingKeyOrValueAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la requête ne peut pas être vide..
        /// </summary>
        public static string BindingMissingRequestBodyRequiredValueAccessor {
            get {
                return ResourceManager.GetString("BindingMissingRequestBodyRequiredValueAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La valeur &apos;{0}&apos; n&apos;est pas valide..
        /// </summary>
        public static string BindingNonPropertyAttemptedValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("BindingNonPropertyAttemptedValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La valeur spécifiée est invalide..
        /// </summary>
        public static string BindingNonPropertyUnknownValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("BindingNonPropertyUnknownValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ dit être un nombre..
        /// </summary>
        public static string BindingNonPropertyValueMustBeANumberAccessor {
            get {
                return ResourceManager.GetString("BindingNonPropertyValueMustBeANumberAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La valeur spécifiée est invalide pour {0}..
        /// </summary>
        public static string BindingUnknownValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("BindingUnknownValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La valeur &apos;{0}&apos; est invalide..
        /// </summary>
        public static string BindingValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("BindingValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &apos;{0}&apos; doit être un nombre..
        /// </summary>
        public static string BindingValueMustBeANumberAccessor {
            get {
                return ResourceManager.GetString("BindingValueMustBeANumberAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La valeur &apos;{0}&apos; est invalide..
        /// </summary>
        public static string BindingValueMustNotBeNullAccessor {
            get {
                return ResourceManager.GetString("BindingValueMustNotBeNullAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&quot;âge doit être compris entre {1} et {2} ans..
        /// </summary>
        public static string BirthDateFormatAttribute {
            get {
                return ResourceManager.GetString("BirthDateFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La valeur de {0} doit être cochée..
        /// </summary>
        public static string CheckBoxAttribute {
            get {
                return ResourceManager.GetString("CheckBoxAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} et {1} ne correspondent pas..
        /// </summary>
        public static string CompareAttribute {
            get {
                return ResourceManager.GetString("CompareAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} n&apos;est pas un numéro de carte valide..
        /// </summary>
        public static string CreditCardAttribute {
            get {
                return ResourceManager.GetString("CreditCardAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le type de données attendu pour le champ {0} est {1}..
        /// </summary>
        public static string DataTypeAttribute {
            get {
                return ResourceManager.GetString("DataTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La {0} doit contenir au moins {2} et au plus {1} caractères..
        /// </summary>
        public static string DescriptionFormatAttribute {
            get {
                return ResourceManager.GetString("DescriptionFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} n&apos;est pas valide..
        /// </summary>
        public static string DeviceIdFormatAttribute {
            get {
                return ResourceManager.GetString("DeviceIdFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;{0} n&apos;est pas une adresse mail valide..
        /// </summary>
        public static string EmailAddressAttribute {
            get {
                return ResourceManager.GetString("EmailAddressAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse email est invalide..
        /// </summary>
        public static string EmailFormatAttribute {
            get {
                return ResourceManager.GetString("EmailFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} doit représenter un élément de liste attendu..
        /// </summary>
        public static string EnumDataTypeAttribute {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la silhouette n&apos;est pas valide..
        /// </summary>
        public static string FigureFormatAttribute {
            get {
                return ResourceManager.GetString("FigureFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} accepte seulement les fichiers de type : {1}.
        /// </summary>
        public static string FileExtensionsAttribute {
            get {
                return ResourceManager.GetString("FileExtensionsAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} doit contenir au moins {2} caractères et au plus {1} caractères..
        /// </summary>
        public static string FirstNameFormatAttribute {
            get {
                return ResourceManager.GetString("FirstNameFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} n&apos;est pas valide..
        /// </summary>
        public static string GenderFormatAttribute {
            get {
                return ResourceManager.GetString("GenderFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le valeur de {0} doit être comprise entre {1} et {2}..
        /// </summary>
        public static string HeightFormatAttribute {
            get {
                return ResourceManager.GetString("HeightFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} doit contenir au moins {2} caractères et au plus {1} caractères..
        /// </summary>
        public static string LastNameFormatAttribute {
            get {
                return ResourceManager.GetString("LastNameFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} doit est une chaîne ou un tableau de longueur maximale {1}..
        /// </summary>
        public static string MaxLengthAttribute {
            get {
                return ResourceManager.GetString("MaxLengthAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} doit est une chaîne ou un tableau de longueur minimale {1}..
        /// </summary>
        public static string MinLengthAttribute {
            get {
                return ResourceManager.GetString("MinLengthAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} doit contenir uniquement des chiffres entre {1} et {2}..
        /// </summary>
        public static string PasswordDigitAttribute {
            get {
                return ResourceManager.GetString("PasswordDigitAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} doit contenir au moins {2} chiffres et au plus {1}..
        /// </summary>
        public static string PasswordDigitFormatAttribute {
            get {
                return ResourceManager.GetString("PasswordDigitFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} n&apos;est pas valide..
        /// </summary>
        public static string PhoneAttribute {
            get {
                return ResourceManager.GetString("PhoneAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} n&apos;est pas valide..
        /// </summary>
        public static string PhoneFormatAttribute {
            get {
                return ResourceManager.GetString("PhoneFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} n&apos;est pas une url valide pour http, https ou ftp..
        /// </summary>
        public static string PortraitFormatAttribute {
            get {
                return ResourceManager.GetString("PortraitFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le valeur de {0} doit être comprise entre {1} et {2}..
        /// </summary>
        public static string RangeAttribute {
            get {
                return ResourceManager.GetString("RangeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le valeur de {0} doit être comprise entre {1} et {2}..
        /// </summary>
        public static string RatingFormatAttribute {
            get {
                return ResourceManager.GetString("RatingFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} doit contenir au moins {2} caractères et au plus {1} caractères..
        /// </summary>
        public static string ReasonFormatAttribute {
            get {
                return ResourceManager.GetString("ReasonFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La valeur de {0} doit correspondre à l&apos;expression régulière &apos;{1}&apos;..
        /// </summary>
        public static string RegularExpressionAttribute {
            get {
                return ResourceManager.GetString("RegularExpressionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} est obligatoire..
        /// </summary>
        public static string RequiredAttribute {
            get {
                return ResourceManager.GetString("RequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} doit contenir exactement {1} chiffres..
        /// </summary>
        public static string ReturnCodeFormatAttribute {
            get {
                return ResourceManager.GetString("ReturnCodeFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} doit contenir au moins {2} caractères et au plus {1} caractères et correspondre à l&apos;expression régulière &apos;{3}&apos;..
        /// </summary>
        public static string ReturnTokenFormatAttribute {
            get {
                return ResourceManager.GetString("ReturnTokenFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} n&apos;est pas un rôle valide..
        /// </summary>
        public static string RoleFormatAttribute {
            get {
                return ResourceManager.GetString("RoleFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} doit contenir au moins {2} caractères et au plus {1} caractères..
        /// </summary>
        public static string StringLengthAttribute {
            get {
                return ResourceManager.GetString("StringLengthAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} n&apos;est pas valide..
        /// </summary>
        public static string TargetFormatAttribute {
            get {
                return ResourceManager.GetString("TargetFormatAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} n&apos;est pas une url valide pour http, https ou ftp..
        /// </summary>
        public static string UrlAttribute {
            get {
                return ResourceManager.GetString("UrlAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le valeur de {0} doit être comprise entre {1} et {2}..
        /// </summary>
        public static string WeightFormatAttribute {
            get {
                return ResourceManager.GetString("WeightFormatAttribute", resourceCulture);
            }
        }
    }
}
