//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpandables.Net.Primitives.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18nXpandables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18nXpandables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xpandables.Net.Primitives.I18n.I18nXpandables", typeof(I18nXpandables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;action &apos;{0}&apos; a échoué. Voir les détails dans l&apos;exception..
        /// </summary>
        public static string ActionSpecifiedFailedSeeException {
            get {
                return ResourceManager.GetString("ActionSpecifiedFailedSeeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echec de l&apos;ajout de l&apos;aggrégat..
        /// </summary>
        public static string AggregateFailedToAppend {
            get {
                return ResourceManager.GetString("AggregateFailedToAppend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echec à la création de l&apos;aggrégat de type &apos;{0}&apos;..
        /// </summary>
        public static string AggregateFailedToCreateInstance {
            get {
                return ResourceManager.GetString("AggregateFailedToCreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de convertisseur trouvé pour le type évènement &apos;{0}&apos;..
        /// </summary>
        public static string AggregateFailedToFindConverter {
            get {
                return ResourceManager.GetString("AggregateFailedToFindConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de filtre trouvé pour le type d&apos;entité &apos;{0}&apos;..
        /// </summary>
        public static string AggregateFailedToFindFilter {
            get {
                return ResourceManager.GetString("AggregateFailedToFindFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de snapshot trouvé pour l&apos;id {0}..
        /// </summary>
        public static string AggregateFailedToFindSnapshot {
            get {
                return ResourceManager.GetString("AggregateFailedToFindSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echec d lecture de l&apos;aggrégat..
        /// </summary>
        public static string AggregateFailedToRead {
            get {
                return ResourceManager.GetString("AggregateFailedToRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ne peut pas être vide.
        /// </summary>
        public static string CanNotBeNull {
            get {
                return ResourceManager.GetString("CanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La déserialisation du type &apos;{0}&apos; a échoué..
        /// </summary>
        public static string EventConverterFailedToDeserialize {
            get {
                return ResourceManager.GetString("EventConverterFailedToDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;évènement avec la même clé {0} existe déjà dans la collection..
        /// </summary>
        public static string EventSourcingDomainEventAlreadyExist {
            get {
                return ResourceManager.GetString("EventSourcingDomainEventAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La notification {0} existe déjà dans la collection..
        /// </summary>
        public static string EventSourcingEventIntegrationAlreadyExists {
            get {
                return ResourceManager.GetString("EventSourcingEventIntegrationAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de Domain Event Handler trouvé pour &apos;{0}&apos;.
        /// </summary>
        public static string EventSourcingNoDomainEventHandler {
            get {
                return ResourceManager.GetString("EventSourcingNoDomainEventHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas d&apos;Integration Event Handler trouvé pour &apos;{0}&apos;.
        /// </summary>
        public static string EventSourcingNoIntegrationEventHandler {
            get {
                return ResourceManager.GetString("EventSourcingNoIntegrationEventHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflit Trouvé.
        /// </summary>
        public static string HttpStatusCodeConflict {
            get {
                return ResourceManager.GetString("HttpStatusCodeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exécution Refusée.
        /// </summary>
        public static string HttpStatusCodeForbidden {
            get {
                return ResourceManager.GetString("HttpStatusCodeForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur Interne.
        /// </summary>
        public static string HttpStatusCodeInternalServerError {
            get {
                return ResourceManager.GetString("HttpStatusCodeInternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Indisponible.
        /// </summary>
        public static string HttpStatusCodeLocked {
            get {
                return ResourceManager.GetString("HttpStatusCodeLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrement Non Trouvé.
        /// </summary>
        public static string HttpStatusCodeNotFound {
            get {
                return ResourceManager.GetString("HttpStatusCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulter l&apos;erreur ou contacter l&apos;administrateur pour plus de détails.
        /// </summary>
        public static string HttpStatusCodeProblemDetailInternalError {
            get {
                return ResourceManager.GetString("HttpStatusCodeProblemDetailInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulter les erreurs pour plus de détails.
        /// </summary>
        public static string HttpStatusCodeProblemDetailPropertyError {
            get {
                return ResourceManager.GetString("HttpStatusCodeProblemDetailPropertyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur de Validation.
        /// </summary>
        public static string HttpStatusCodeRequestValidation {
            get {
                return ResourceManager.GetString("HttpStatusCodeRequestValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accès Non Autorisé.
        /// </summary>
        public static string HttpStatusCodeUnauthorized {
            get {
                return ResourceManager.GetString("HttpStatusCodeUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de parser le document &apos;{0}&apos;..
        /// </summary>
        public static string JsonDocumentFailedToParse {
            get {
                return ResourceManager.GetString("JsonDocumentFailedToParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de convertir un model valide en opération d&apos;erreur.
        /// </summary>
        public static string OperationResultCanNotConvertModelState {
            get {
                return ResourceManager.GetString("OperationResultCanNotConvertModelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de résultat à l&apos;exécution de la tâche..
        /// </summary>
        public static string OperationResultValueIsNull {
            get {
                return ResourceManager.GetString("OperationResultValueIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echec de l&apos;ajout de la notification..
        /// </summary>
        public static string OutboxFailedToAppendEventIntegration {
            get {
                return ResourceManager.GetString("OutboxFailedToAppendEventIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accès impossible au chemin de l&apos;assembly..
        /// </summary>
        public static string PathAssemblyUnavailable {
            get {
                return ResourceManager.GetString("PathAssemblyUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le type {0} doit implémenter {1}..
        /// </summary>
        public static string TypeMustImplement {
            get {
                return ResourceManager.GetString("TypeMustImplement", resourceCulture);
            }
        }
    }
}
