/*******************************************************************************
 * Copyright (C) 2025-2026 Kamersoft
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
********************************************************************************/

using System.ComponentModel;

namespace System.Requests.AsyncPaged;

/// <summary>
/// Defines a handler for processing stream requests asynchronously, producing a paged stream of responses.
/// </summary>
/// <remarks>This interface extends <see cref="IRequestHandler{TRequest}"/> to support handling requests that
/// result in a stream of responses. Implementations should ensure that the stream is properly disposed of and that any
/// necessary cleanup is performed.</remarks>
/// <typeparam name="TRequest">The type of the request message.</typeparam>
/// <typeparam name="TResponse">The type of the response message.</typeparam>
public interface IRequestStreamPagedHandler<in TRequest, TResponse> : IRequestHandler<TRequest>
	where TRequest : class, IRequestStreamPaged<TResponse>
{
	/// <summary>
	/// Asynchronously handles the specified request and returns a paged stream of responses.
	/// </summary>
	/// <param name="request">The request to be processed.</param>
	/// <param name="cancellationToken">A token to monitor for cancellation requests.</param>
	/// <returns>A task that represents the asynchronous operation, containing a paged stream of responses.</returns>
	new Task<Result<IAsyncPagedEnumerable<TResponse>>> HandleAsync(
		TRequest request,
		CancellationToken cancellationToken = default);

	[EditorBrowsable(EditorBrowsableState.Never)]
	async Task<Result> IRequestHandler<TRequest>.HandleAsync(
		TRequest request, CancellationToken cancellationToken) =>
		await HandleAsync(request, cancellationToken).ConfigureAwait(false);
}

/// <summary>
/// Defines a handler for processing paged stream-based requests within a specific request context.
/// </summary>
/// <remarks>This interface extends <see cref="IRequestStreamPagedHandler{TRequest, TResponse}"/> by providing
/// additional context-aware handling capabilities through the <see cref="RequestContext{TRequest}"/>.</remarks>
/// <typeparam name="TRequest">The type of the request being handled. Must implement <see cref="IRequestStreamPaged{TResponse}"/>.</typeparam>
/// <typeparam name="TResponse">The type of the response elements produced by the stream.</typeparam>
public interface IRequestStreamPagedContextHandler<TRequest, TResponse> : IRequestStreamPagedHandler<TRequest, TResponse>
	where TRequest : class, IRequestStreamPaged<TResponse>
{
	/// <summary>
	/// Handles the specified request asynchronously and returns the result of the operation.
	/// </summary>
	/// <remarks>This method processes the request asynchronously and supports streaming responses via <see
	/// cref="IAsyncEnumerable{T}"/>. The caller can enumerate the responses as they are produced.</remarks>
	/// <param name="context">The request context containing the input data and metadata required to process the request.</param>
	/// <param name="cancellationToken">A token to monitor for cancellation requests. The default value is <see cref="CancellationToken.None"/>.</param>
	/// <returns>A task that represents the asynchronous operation. The task result contains an <see cref="Result{T}"/>
	/// wrapping an <see cref="IAsyncEnumerable{T}"/> of <typeparamref name="TResponse"/> objects, representing the
	/// responses generated by the handler.</returns>
	Task<Result<IAsyncPagedEnumerable<TResponse>>> HandleAsync(
		RequestContext<TRequest> context,
		CancellationToken cancellationToken = default);

	[EditorBrowsable(EditorBrowsableState.Never)]
	async Task<Result<IAsyncPagedEnumerable<TResponse>>> IRequestStreamPagedHandler<TRequest, TResponse>.HandleAsync(
		TRequest request, CancellationToken cancellationToken) =>
		await HandleAsync(new(request), cancellationToken).ConfigureAwait(false);
}
