/*******************************************************************************
 * Copyright (C) 2025 Kamersoft
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
********************************************************************************/
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xpandables.Net.Optionals;

/// <summary>
/// JSON converter factory for Optional&lt;T&gt; types, providing AOT-compatible serialization for .NET 10.
/// The implementation is auto-generated by OptionalJsonConverterGenerator based on:
/// <list type="bullet">
/// <item>Types declared with [JsonSerializable] attributes in <see cref="OptionalJsonContext"/></item>
/// <item>Optional&lt;T&gt; types discovered through code analysis in the consuming project</item>
/// </list>
/// </summary>
public sealed partial class OptionalJsonConverterFactory : JsonConverterFactory
{
    /// <inheritdoc/>
    public override bool CanConvert(Type typeToConvert)
    {
        ArgumentNullException.ThrowIfNull(typeToConvert);

        if (!typeToConvert.IsGenericType)
            return false;

        var genericTypeDef = typeToConvert.GetGenericTypeDefinition();
        return genericTypeDef == typeof(Optional<>);
    }

    /// <inheritdoc/>
    public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(typeToConvert);
        ArgumentNullException.ThrowIfNull(options);

        if (options.TypeInfoResolverChain.FirstOrDefault(resolver => resolver is OptionalJsonContext) is null)
        {
            options.TypeInfoResolverChain.Add(OptionalJsonContext.Default);
        }

        var valueType = typeToConvert.GetGenericArguments()[0];
        var converterType = typeof(OptionalJsonConverter<>).MakeGenericType(valueType);
        return (JsonConverter)Activator.CreateInstance(converterType)!;
    }
}
